package com.shoppingapi.datastore.dataprovider.entity.dynamodb

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import org.springframework.stereotype.Component
import java.util.*

@DynamoDBTable(tableName = "Invoice_Info")
@Component
class Invoice  {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "invoiceId")
    lateinit var invoiceId: String

    @DynamoDBAttribute(attributeName = "dispatch")
    var dispatch: Boolean = false

    @DynamoDBAttribute(attributeName = "dispatchDate")
    lateinit var dispatchDate: Date

    constructor()

    constructor(invoiceId: String, dispatch: Boolean, dispatchDate: Date) {
        this.invoiceId = invoiceId
        this.dispatch = dispatch
        this.dispatchDate = dispatchDate
    }
}