version: "3.0"

services:
  db-postgres:
    container_name: postgres_container
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: shoppingapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: System20
    volumes:
      - db-postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: System20
    ports:
      - "16543:80"
    depends_on:
      - db-postgres

  aws-localstack:
    container_name: aws-localstack
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8000}:${PORT_WEB_UI-8000}"
    environment:
      - SERVICES=secretsmanager,ssm,sts,acm,dynamodb
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=AKIA6ISFFOL2UYYT3WX4
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_SESSION_TOKEN=AKIA6ISFFOL2UYYT3WX4kCoIpN9NcPBSZVbf7UGgC6/5coA09jPJwaho7q2l
      - AWS_DEFAULT_REGION=sa-east-1
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - START_WEB=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - dev-net

  aws-secrets-manager:
    container_name: aws-secrets-manager
    image: amazon/aws-cli
    depends_on:
      - aws-localstack
    entrypoint: /bin/sh -c
    command: >
      "aws --endpoint http://host.docker.internal:4566 secretsmanager create-secret --name 'sts-credentials-test' --description 'Segredo para efetuar um teste com LocalStack' --secret-string '{\"client-id\":\"fakeaccess\",\"client-secret\":\"fakesecret\"}' --region 'sa-east-1'"
    restart: on-failure:5
    environment:
      AWS_ACCESS_KEY_ID: AKIA6ISFFOL2UYYT3WX4
      AWS_SECRET_ACCESS_KEY: kCoIpN9NcPBSZVbf7UGgC6/5coA09jPJwaho7q2l
      AWS_DEFAULT_REGION: sa-east-1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/health" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - dev-net

volumes:
  db-postgres:
    driver: local

networks:
  dev-net:
    driver:
      bridge