/*
 * This file was generated by the Gradle 'init' task.
 */
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

configurations.all() {
    exclude("org.springframework.boot", "spring-boot-starter-tomcat")
}

plugins {
    id("application")
    id("org.springframework.boot")
    id("io.spring.dependency-management") version "1.0.12.RELEASE"
    kotlin("jvm")
    kotlin("plugin.spring")
    id("info.solidsoft.pitest") version "1.7.4"
}

group = "shopping.app"
version = "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    // Open Api
    implementation("org.springdoc:springdoc-openapi-data-rest:1.6.0")
    implementation("org.springdoc:springdoc-openapi-ui:1.6.0")
    implementation("org.springdoc:springdoc-openapi-kotlin:1.6.0")

    // Others
    implementation("org.springframework.boot:spring-boot-starter-web") {
        exclude("org.springframework.boot", "spring-boot-starter-tomcat")
    }
    implementation("org.springframework.boot:spring-boot-starter-undertow")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-validation")

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    implementation(kotlin("script-runtime"))

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
    testImplementation("org.junit.platform:junit-platform-launcher:1.9.0")

    // mockk
    testImplementation("io.mockk:mockk:1.4.1")

    // pitest
    implementation("info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.7.4")

    // projects
    implementation(project(":domain"))
    implementation(project(":core"))
}

apply(plugin = "info.solidsoft.pitest")
apply(plugin = "info.solidsoft.pitest.aggregator")
apply(plugin = "io.spring.dependency-management")

the<io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension>().apply {
    imports {
        mavenBom(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
    }
}

tasks.test {
    useJUnitPlatform()
    dependsOn(":http:pitest")
}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "11"
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict", "-Xemit-jvm-type-annotations")
    }
}

pitest {
    targetClasses.add("com.shoppingapi.*")
    targetTests.add("com.shoppingapi.*Test")
    testSourceSets.add(sourceSets.test)
    mainSourceSets.add(sourceSets.main)
    jvmArgs.addAll("-Xmx1024m", "-Dspring.test.constructor.autowire.mode=all")
    useClasspathFile.set(true)     //useful with bigger projects on Windows
    fileExtensionsToFilter.addAll("xml", "orbit")
    outputFormats.addAll("XML", "HTML")
    timestampedReports.set(false)
    junit5PluginVersion.set("0.15")
    exportLineCoverage.set(true)
}