
## Springboot config!

########################################################
# SWAGGER DOCS API                                     #
########################################################

#springdoc swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packagesToScan: com.shoppingapi.app.entrypoint
  pathsToMatch: /**

#spring:
#  profiles:
#    active: test
  mustache:
    check-template-location: false
  jmx:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://host.docker.internal:5432/shoppingapi}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:System20}
    entityPackage: com.shoppingapi.core.datastore.entity.postgres
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    baselineVersion: 0
#    schemas:
#      - shoppingapi.public
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DURATIONS_AS_TIMESTAMPS: false

########################################################
# APP SERVICES PATH                                    #
########################################################
server:
  port : 9182
  servlet:
    context-path: /shopping_api

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: error
    org.hibernate: debug

########################################################
# Aws DynamoDB Datasource                              #
########################################################
amazon:
  dynamodb:
    endpoint: http://localhost:4566
  aws:
    region: sa-east-1
    accesskey: key
    secretkey: key2